apiVersion: v1
kind: Service
metadata:
  name: flask-webhook-svc
  labels:
    app: flask-webhook
spec:
  ports:
    - port: 5443
      targetPort: 5443
      protocol: TCP
  selector:
    app: flask-webhook
